ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VEHICLE_MARKETPLACE_INQUIRY_REPLY_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'JOB_APPLICATION_SUBMISSION_REPLY_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BID_REPLY_CREATED';
