ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BID_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BID_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CONTRACT_STATUS_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VEHICLE_MARKETPLACE_INQUIRY_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'VEHICLE_MARKETPLACE_INQUIRY_RESPONDED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'JOB_APPLICATION_SUBMITTED';
